[https://school.programmers.co.kr/learn/courses/30/lessons/131117], 5월 식품들의 총매출 조회하기

SELECT
    a.PRODUCT_ID,
    PRODUCT_NAME,
    SUM(AMOUNT * PRICE) AS TOTAL_SALES
FROM FOOD_PRODUCT a
JOIN FOOD_ORDER b ON a.PRODUCT_ID = b.PRODUCT_ID
WHERE PRODUCE_DATE LIKE '2022-05%'
GROUP BY PRODUCT_ID
ORDER BY TOTAL_SALES DESC, a.PRODUCT_ID;
