//@formatter:off
//ORACLE

-- level 3

-- 조회 수가 가장 많은 중고거래 게시판의 첨부파일 조회하기
SELECT CONCAT('/home/grep/src/', FILE.BOARD_ID, '/', FILE_ID || FILE_NAME || FILE_EXT) AS FILE_PATH
FROM USED_GOODS_FILE FILE
LEFT JOIN USED_GOODS_BOARD BOARD
ON FILE.BOARD_ID = BOARD.BOARD_ID
WHERE VIEWS = (SELECT MAX(VIEWS) FROM USED_GOODS_BOARD)
ORDER BY FILE.FILE_ID DESC;


-- 조건별로 분류하여 주문상태 출력하기
SELECT ORDER_ID,
       PRODUCT_ID,
       TO_CHAR(OUT_DATE, 'YYYY-MM-DD') as OUT_DATE,
       CASE
            WHEN OUT_DATE IS NULL THEN '출고미정'
            WHEN OUT_DATE <= TO_DATE('2022-05-01', 'YYYY-MM-DD') THEN '출고완료'
            WHEN OUT_DATE > TO_DATE('2022-05-01', 'YYYY-MM-DD') THEN '출고대기'
       END as 출고여부
FROM FOOD_ORDER
ORDER BY ORDER_ID ASC;


-- 오랜 기간 보호한 동물(1)
SELECT NAME, DATETIME
FROM (
    SELECT ANIMAL_INS.NAME, ANIMAL_INS.DATETIME
    FROM ANIMAL_INS LEFT OUTER JOIN ANIMAL_OUTS
    ON ANIMAL_INS.ANIMAL_ID = ANIMAL_OUTS.ANIMAL_ID
    WHERE ANIMAL_OUTS.ANIMAL_ID IS NULL
    ORDER BY ANIMAL_INS.DATETIME
)
WHERE ROWNUM <= 3;

//@formatter:off